---
tasks:
- package:
    comment: install apache2 package
    name: apache2
    action: install
        
- file:
    comment: create file in /var/www/html/index.html
    path: /var/www/html/index.html
    owner: root
    group: root
    mode: 755
    content: "Hello, world!"
    action: create

- service:
    comment: start service apache2
    name: apache2
    action: start
